# simple makefile

# DO NOT FORGET to define BITBOX environment variable 

NO_USB=1

# 2 to 5, see lib/simple.h for modes 
VGA_SIMPLE_MODE=4

NAME = test_simplegraph
GAME_C_FILES = $(NAME).c 

# see this file for options
include $(BITBOX)/lib/bitbox.mk

