# simple makefile

# DO NOT FORGET to define BITBOX environment variable 

NO_USB=1
NO_SDCARD=1

# See lib/simple.h for modes 
VGA_SIMPLE_MODE=4

NAME = sgraph
GAME_C_FILES = $(NAME).c 

# see this file for options
include $(BITBOX)/lib/bitbox.mk

