# simple makefile

# DO NOT FORGET to define BITBOX environment variable

NO_USB=1

# see lib/simple.h for modes (graphical)
VGA_SIMPLE_MODE=5

NAME = test_simplegraph
GAME_C_FILES = $(NAME).c lib/simple.c

# see this file for options
include $(BITBOX)/kernel/bitbox.mk

