#testkernel makefile
NO_SDCARD=1
NO_AUDIO=1

# set kernel interface to either 8 or 16 bits. Set either MICROKERNEL=1 or AUTOKERNEL=1
MICROKERNEL=1

DEFINES = VGAMODE_400 PROFILE

NAME = crappy
GAME_C_FILES = crappy.c 
include $(BITBOX)/lib/bitbox.mk
