# simple makefile
NO_USB=1

# See lib/simple.c for modes
VGA_SIMPLE_MODE=1   # 0 or 1 allowed in this example.  do `make clean` if you change it.

NAME = stext

GAME_C_FILES = test_simple_txt.c 

# bitbox_simple.mk, will include files by default
include $(BITBOX)/lib/bitbox.mk
