# simple makefile
NO_USB=1

# See lib/simple.c for modes
VGA_SIMPLE_MODE=12

NAME = stext

GAME_C_FILES = test_simple_txt_color.c 

# bitbox_simple.mk, will include files by default
include $(BITBOX)/lib/bitbox.mk
